name: build_deploy_aks

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: string
        default: 'Dev' # Default to Dev environment if not specified

jobs:
  build_dev:
    runs-on: ubuntu-latest
    if: github.event.inputs.environment == 'Dev'
    steps:
      - name: Checkout source code 
        uses: actions/checkout@v3
      - name: Use Dev secrets
        run: |
          echo "SECRET_1=${{ secrets.dev_secret_1 }}" >> $GITHUB_ENV
          echo "SECRET_2=${{ secrets.dev_secret_2 }}" >> $GITHUB_ENV
      - name: ACR build
        id: build-push-acr
        uses: azure/acr-build@v1
        with:
          service_principal: ${{ secrets.SERVICE_PRINCIPAL_DEV }}
          service_principal_password: ${{ secrets.SERVICE_PRINCIPAL_PASSWORD_DEV }}
          tenant: ${{ secrets.TENANT_DEV }}
          registry: ${{ secrets.REGISTRY_DEV }}
          repository: ${{ secrets.REPOSITORY_DEV }}
          image:  azure-vote-front
          folder: azure-vote
          branch: master
          tag: ${{ github.sha }}
      # Additional steps as needed for Dev environment

  build_prod:
    runs-on: ubuntu-latest
    if: github.event.inputs.environment == 'Prod'
    steps:
      - name: Checkout source code 
        uses: actions/checkout@v3
      - name: Use Prod secrets
        run: |
          echo "SECRET_1=${{ secrets.prod_secret_1 }}" >> $GITHUB_ENV
          echo "SECRET_2=${{ secrets.prod_secret_2 }}" >> $GITHUB_ENV
      - name: ACR build
        id: build-push-acr
        uses: azure/acr-build@v1
        with:
          service_principal: ${{ secrets.SERVICE_PRINCIPAL_PROD }}
          service_principal_password: ${{ secrets.SERVICE_PRINCIPAL_PASSWORD_PROD }}
          tenant: ${{ secrets.TENANT_PROD }}
          registry: ${{ secrets.REGISTRY_PROD }}
          repository: ${{ secrets.REPOSITORY_PROD }}
          image:  azure-vote-front
          folder: azure-vote
          branch: master
          tag: ${{ github.sha }}
      # Additional steps as needed for Prod environment

